### ISSUE TITLE
can't sync all labels

### ISSUE THREAD

**Issue by bachoudev** [Xunnamius/gitlab-fix-labels#4]
If you import many new labels (more than 20) you will only get 20 new labels in your project page.

Gitlab api limit a page at 20 elements

To fix that adding L176 `?per_page=100` this is not the best solution but at least you can sync more than 20 labels.
https://github.com/Xunnamius/gitlab-fix-labels/blob/cc974228feb2728b5051dbeba4ba9e62523b29f2/lib/gitlab-fix-labels.js#L176

**Comment by Xunnamius** [comment]
Nice catch, I'll add it in. I'm a bit bogged down with work now, but I'll accept a PR :)

**Comment by bachoudev** [comment]
No problem i will open a PR this week. 
I just see there is defaut parameters already with a per_page but it not seems to be working maybe i need to look more into it to do something clean

```js
const requestDefaults = {
    method: 'GET',
    json: true,
    page: 1,
    per_page: 100, // eslint-disable-line camelcase
};
```

**Comment by Xunnamius** [comment]
Coincidentally, I started working on this about an hour ago! I believe the problem was that I put the default parameters under the wrong key. For the request package I'm using, query string parameters need to be under the `qs` key.

The problem should be fixed now, though I don't run my own local GitLab instance anymore so I can't test it. Does the latest version work for you?

**Comment by bachoudev** [comment]
I just test on my gitlab no problem on my side. Thanks !
